### ISSUE TITLE
Compile failed on Mac OSX arm64

### ISSUE THREAD

**Issue by rsaue** [willardharris/linhpsdr#1]
Hi,
compiling on av Mac gives compile/linking error with undefined symbols for architecture arm64:

---- snipp --- 

1 warning generated.
gcc -o linhpsdr main.o audio.o version.o discovered.o discovery.o protocol1_discovery.o protocol2_discovery.o property.o mode.o filter.o band.o radio.o receiver.o transmitter.o vfo.o meter.o rx_panadapter.o tx_panadapter.o mic_level.o mic_gain.o drive_level.o wideband_panadapter.o wideband_waterfall.o waterfall.o protocol1.o protocol2.o radio_dialog.o receiver_dialog.o transmitter_dialog.o pa_dialog.o eer_dialog.o wideband_dialog.o about_dialog.o button_text.o wideband.o vox.o ext.o configure_dialog.o bookmark_dialog.o puresignal_dialog.o oc_dialog.o xvtr_dialog.o frequency.o rigctl.o error_handler.o radio_info.o bpsk.o css.o subrx.o  mac_midi.o midi2.o midi3.o midi_dialog.o  `pkg-config --libs gtk+-3.0` -lm -lpthread -lwdsp -framework CoreMIDI -framework Foundation -lsoundio  
Undefined symbols for architecture arm64:
  "_create_noise_menu_dialog", referenced from:
      _create_configure_dialog in configure_dialog.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [linhpsdr] Error 1

---- snipp --- 

I am using av Mac Mini G4 with latest OSX software... Additional libraries for building per Readme. MD downloaded and installed with brew.

Compiles ok using G0ORX code. 

73 de LB2EG Richard

**Comment by willardharris** [comment]
I do not have a MAC, but I updated the MAC makefile to include the new noise menu.  Do a git pull and try compile again.  Let me know of any new errors and we will work through them.

**Comment by willardharris** [comment]
I also merged in the G0ORX  fix

**Comment by rsaue** [comment]
Hi,
Now it compiles OK on the Mac. 

Before the changes I had problems to compile also on Ubuntu Linux 25.04 on a RPI5 and a AMD x64 system, only working with Ubuntu 24.04.2 on the AMD x64. Testing on the RPI5 this morning, all worked OK also there.  Will let you know if I still have problems on the AMD x64....  

73 de LB2EG Richard

**Comment by rsaue** [comment]
All OK also on Ubuntu 25.04 on AMD x64. 

Send me a note if you want a copy of compile warnings on my platforms. 

Closing this issue as completed. 

73 e LB2EG Richard
